services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: to-do-list
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - 3307:3306    
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}